"""Rasterize printable ASCII into 4-bit alpha bitmap fonts for firmware/lib/ui.

    python make_font.py OUT.cpp NAME:FONT.ttf:SIZE [NAME:FONT.ttf:SIZE ...]

Dev-time only (needs Pillow); the generated file is committed. The fonts are M PLUS Rounded 1c
(SIL OFL, see firmware/lib/ui/src/OFL.txt), from https://github.com/google/fonts/tree/main/ofl/mplusrounded1c:

    python make_font.py firmware/lib/ui/src/fonts.cpp \\
        small:MPLUSRounded1c-Medium.ttf:12 large:MPLUSRounded1c-Bold.ttf:16
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126  # printable ASCII


def rasterize(ttf, size):
    font = ImageFont.truetype(ttf, size)
    ascent, descent = font.getmetrics()
    height = ascent + descent
    glyphs, alpha = [], []
    for code in range(FIRST, LAST + 1):
        left, _, right, _ = font.getbbox(chr(code))
        width = max(0, right - left)
        image = Image.new("L", (max(width, 1), height), 0)
        ImageDraw.Draw(image).text((-left, 0), chr(code), font=font, fill=255)
        offset = len(alpha)
        for y in range(height):
            row = [image.getpixel((x, y)) >> 4 for x in range(width)]
            row += [0] * (len(row) % 2)  # pad each row to whole bytes: 2 pixels per byte
            alpha += [row[i] << 4 | row[i + 1] for i in range(0, len(row), 2)]
        glyphs.append((offset, width, round(font.getlength(chr(code))), left))
    return height, ascent, glyphs, alpha


def emit(name, ttf, size):
    height, ascent, glyphs, alpha = rasterize(ttf, size)
    rows = ",\n    ".join(", ".join(str(b) for b in alpha[i:i + 24]) for i in range(0, len(alpha), 24))
    table = "\n".join(f"    {{{o}, {w}, {a}, {l}}},  // {chr(FIRST + i)!r}" for i, (o, w, a, l) in enumerate(glyphs))
    return (f"// {os.path.basename(ttf)} at {size} px\n"
            f"namespace {{\nconst uint8_t {name}Alpha[] = {{\n    {rows}}};\n"
            f"const Glyph {name}Glyphs[] = {{\n{table}\n}};\n}}  // namespace\n"
            f"const Font {name} = {{{height}, {ascent}, {name}Glyphs, {name}Alpha}};\n")


def main():
    out, specs = sys.argv[1], sys.argv[2:]
    parts = [emit(name, ttf, int(size)) for name, ttf, size in (s.split(":") for s in specs)]
    with open(out, "w") as f:
        f.write("// Generated by firmware/tools/make_font.py. Do not edit.\n")
        f.write("// M PLUS Rounded 1c, SIL Open Font License 1.1 (see OFL.txt).\n")
        f.write('#include "font.h"\n\nnamespace ui::fonts {\n\n')
        f.write("\n".join(parts))
        f.write("\n}  // namespace ui::fonts\n")


if __name__ == "__main__":
    main()
